apiVersion: v1
kind: Service
metadata:
  name: training-fullstack-be
  namespace: k3s-training
spec:
  type: ClusterIP
  selector:
    app: training-fullstack-be
  ports:
    - port: 3000
      targetPort: 3000
