apiVersion: v1
kind: Service
metadata:
  name: training-fullstack-fe
  namespace: k3s-training
spec:
  type: NodePort
  selector:
    app: training-fullstack-fe
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30083
