apiVersion: v1
kind: Service
metadata:
  name: training-be-only
  namespace: k3s-training
spec:
  type: NodePort
  selector:
    app: training-be-only
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30082
